#!/usr/bin/python3
#SPDX-FileCopyrightText: 2023 Shinnosuke Nonaka 
#SPDX-License-Identifier: BSD-3-Clause
import sys

ans = 0
count = 0

for line in sys.stdin:
    line = line.strip()
    if not line:
        continue 
    try:
        ans += int(line)
    except:
        ans += float(line)
    finally:
    	count += 1

if count > 0:
    print(ans)
    print(ans/count)
